import{S as u,i as l}from"./assets/vendor-5b791d57.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();const f=document.querySelector(".form"),i=document.querySelector(".gallery"),c=document.querySelector("input"),p=new u(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionSelector:"img",captionDelay:250});function m(){const t=document.createElement("span");t.classList.add("loader"),i.parentNode.insertBefore(t,i)}function d(){const t=document.querySelector(".loader");t&&t.remove()}f.addEventListener("submit",t=>{if(t.preventDefault(),c.value.trim()===""){l.error({message:"Your request is missing. Please fill out the form",position:"topCenter"});return}i.innerHTML="",m();const n=c.value;h(n),c.value=""});function h(t){const r=`https://pixabay.com/api/?key=42356211-e192fc2ea90e5ac732e43fabf&q=${t}&image_type=photo&orientation=horizontal&safesearch=true`;fetch(r).then(s=>{if(!s.ok)throw new Error("Failed to fetch images from the server");return s.json()}).then(s=>y(s)).catch(s=>{l.error({message:`An error occurred: ${s.message}`,position:"topCenter"})}).finally(()=>d())}function y(t){if(t.hits.length===0)l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"});else{const n=t.hits.map(r=>`
  <li class="gallery-item">
    <a href="${r.largeImageURL}">
      <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}">
    </a>
    <p><b>Likes: </b>${r.likes}</p>
    <p><b>Views: </b>${r.views}</p>
    <p><b>Comments: </b>${r.comments}</p>
    <p><b>Downloads: </b>${r.downloads}</p>
  </li>`).join("");i.insertAdjacentHTML("beforeend",n),p.refresh()}}
//# sourceMappingURL=commonHelpers.js.map
