import{i as l,S as u}from"./assets/vendor-5b791d57.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))e(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&e(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function e(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();const f=document.querySelector(".form"),i=document.querySelector(".gallery");document.querySelector("div");const c=document.querySelector("input");function p(){const r=document.createElement("span");r.classList.add("loader"),i.parentNode.insertBefore(r,i)}function m(){const r=document.querySelector(".loader");r&&r.remove()}f.addEventListener("submit",r=>{if(r.preventDefault(),c.value.trim()===""){l.error({message:"Your request is missing. Please fill out the form",position:"topCenter"});return}i.innerHTML="",p();const s=c.value;d(s),c.value=""});function d(r){const n=`https://pixabay.com/api/?key=42356211-e192fc2ea90e5ac732e43fabf&q=${r}&image_type=photo&orientation=horizontal&safesearch=true`;fetch(n).then(e=>{if(!e.ok)throw new Error("Failed to fetch images from the server");return e.json()}).then(e=>h(e)).catch(e=>{l.error({message:`An error occurred: ${e.message}`,position:"topCenter"})}).finally(()=>m())}function h(r){if(r.hits.length===0)l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"});else{const s=r.hits.map(e=>`
  <li class="gallery-item">
    <a href="${e.largeImageURL}">
      <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
    </a>
    <p><b>Likes: </b>${e.likes}</p>
    <p><b>Views: </b>${e.views}</p>
    <p><b>Comments: </b>${e.comments}</p>
    <p><b>Downloads: </b>${e.downloads}</p>
  </li>`).join("");i.insertAdjacentHTML("beforeend",s),new u(".gallery a",{captions:!0,captionType:"attr",captionsData:"alt",captionPosition:"bottom",captionSelector:"img",captionDelay:250}).refresh()}}
//# sourceMappingURL=commonHelpers.js.map
